[package]
name = "mk1"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation"
]}

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"