[package]
name = "shellcode2"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = {version = "0.48.0", features = [
	"Win32_System_Memory",
	"Win32_Foundation",
	"Win32_System_Threading",
	"Win32_Security"
]}