[package]
name = "process_hollowing"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = [
    "processthreadsapi",
    "memoryapi",
    "winnt",
    "winbase",        # <-- THIS IS THE MISSING ONE!
    "synchapi",
    "handleapi"
]}