[package]
name = "stealth_spawn"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [
    "processthreadsapi",
    "winbase",
    "minwinbase",
    "libloaderapi"
]}