[package]
name = "shellcode_runner"
version = "0.1.0"
edition = "2024"

[dependencies.winapi]
version = "0.3"
features = [
    "winuser",
    "memoryapi", 
    "processthreadsapi",
    "synchapi",
    "libloaderapi",
    "winbase",
    "wincon"
]